// src/features/finance/expense_list/ExpenseRowActions.tsx
import { FC } from "react";
import { ExpenseEntry, ExpenseTableHandlers } from "@src/lib/types/finance";
import { Pencil, Trash2, Check, X } from "lucide-react";

interface ExpenseRowActionsProps {
	expense: ExpenseEntry;
	isEditing: boolean;
	handlers: ExpenseTableHandlers;
}

const ExpenseRowActions: FC<ExpenseRowActionsProps> = ({
	expense,
	isEditing,
	handlers,
}) => {
	const { handleSaveEdit, handleCancelEdit, handleStartEdit, handleDelete } =
		handlers;

	return (
		<div className="flex items-center justify-center gap-1">
			{isEditing ? (
				<>
					<button onClick={handleSaveEdit} title="Save changes">
						<Check size={14} />
					</button>
					<button onClick={handleCancelEdit} title="Cancel edit">
						<X size={14} />
					</button>
				</>
			) : (
				<>
					<button
						onClick={() =>
							!expense.isAutoGenerated && handleStartEdit(expense)
						}
						disabled={expense.isAutoGenerated}
						title={expense.isAutoGenerated ? "Cannot edit" : "Edit"}
					>
						<Pencil size={14} />
					</button>
					<button
						onClick={() =>
							handleDelete(
								expense.id,
								expense.name,
								expense.isAutoGenerated || false
							)
						}
						disabled={expense.isAutoGenerated}
						title={
							expense.isAutoGenerated ? "Cannot delete" : "Delete"
						}
					>
						<Trash2 size={14} />
					</button>
				</>
			)}
		</div>
	);
};

export default ExpenseRowActions;
