import { FC } from "react";
import { ExpenseEntry } from "@src/features/finance/type";
import Input from "@src/components/ui/input/Input";
import { Lock } from "lucide-react";

interface NameCellProps {
	expense: ExpenseEntry;
	editForm: ExpenseEntry | null;
	isEditing: boolean;
	onEditChange: (field: keyof ExpenseEntry, value: string | number) => void;
	onKeyDown: (e: React.KeyboardEvent<HTMLElement>) => void;
}

/** Name cell for an expense row, read-only or editable. Extracted from ExpenseRow.tsx. */
const NameCell: FC<NameCellProps> = ({
	expense,
	editForm,
	isEditing,
	onEditChange,
	onKeyDown,
}) => {
	if (isEditing) {
		return (
			<Input
				id={`name-${expense.id}`}
				value={editForm?.name || ""}
				onChange={(e) => onEditChange("name", e.target.value)}
				className="w-full text-sm"
				onKeyDown={onKeyDown}
			/>
		);
	}

	return (
		<div className="flex items-center gap-2">
			{expense.isAutoGenerated && (
				<div title="Auto-generated salary">
					<Lock size={12} className="text-gray-500" />
				</div>
			)}
			<div
				className={`truncate ${
					expense.type === "Cr"
						? "text-green-700 dark:text-green-300 font-medium"
						: "text-gray-800 dark:text-gray-200"
				}`}
				title={expense.name}
			>
				{expense.name}
			</div>
		</div>
	);
};

export default NameCell;
