version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
        ports:
            - "5173:5173"
        volumes:
            - .:/app
            - /app/node_modules
        command: yarn dev
