import { RefObject } from "react";

export type TimeUnit =
	| "yearly"
	| "semiannual"
	| "quarterly"
	| "monthly"
	| "weekly"
	| "daily";

export type ViewMode = "list" | "graph" | "salary" | "estimate";
export type BalanceChangeType = "salary" | "expense" | "manual";

export interface BalanceSectionProps {
	balance?: number; // Total current balance
	expenses?: number; // Total expenses
	remaining?: number; // Optional - you mentioned you might not need this
	simulatedRemaining?: number; // Optional simulated balance
	viewMode?: ViewMode;
}

export interface SummaryItemProps {
	label: string;
	value: string;
}

export interface ExpenseSummaryProps extends BalanceSectionProps {
	onChangeView: (mode: ViewMode) => void;
}

/**
 * A salary configuration with a target payday.
 *
 * `dayOfMonth` is the user's chosen payday (1-31). It is intentionally
 * NOT removed -- getSalaryCreditDate() in finance.ts clamps it to the
 * last actual day of any given month, so e.g. dayOfMonth=31 correctly
 * credits on Feb 28/29 in February instead of overflowing into March.
 * (An earlier comment here claimed this field had been removed in favor
 * of always using end-of-month; that never happened in the code and the
 * comment was stale. This describes the real, current behavior.)
 */
export interface DatedSalary {
	amount: number;
	dayOfMonth: number;
}

export interface FinanceState {
	salary: DatedSalary | null;
	currentBalance: number;
	manualOverride: boolean;
	groups: string[];
	loaded: boolean;
	lastUpdatedDate?: string;
}

export interface ControlsProps {
	viewMode: ViewMode;
	onChangeView: (mode: ControlsProps["viewMode"]) => void;
}

export interface ExpenseEntry {
	id: string;
	date: string; // ISO date string
	group: string;
	name: string;
	amount: number;
	quantity?: number;
	unit?: string;
	type?: "Dr" | "Cr";
	isAutoGenerated?: boolean;
}

export type TableRowRef = RefObject<HTMLTableRowElement | null>;

export interface SimulatedExpense {
	id: string;
	name: string;
	quantity: number;
	unit: string;
	amount: number;
}

export type DateFilter =
	| "today"
	| "yesterday"
	| "weekly"
	| "monthly"
	| "yearly";

export interface Expense {
	date: string;
	amount: number;
	group: string;
	type?: "Dr" | "Cr";
}
