// src/features/finance/expense_list/useExpenseTable.ts
import { useState, useRef } from "react";
import { ExpenseEntry } from "@src/features/finance/type";
import { TableHandlers } from "@src/lib/types/table";
import { ShowNotificationFn } from "@src/lib/types/downloadHandlerTypes";
import { useConfirmedDelete } from "@src/features/finance/hooks/useConfirmedDelete";
import { useEditRowKeyNavigation } from "@src/features/finance/hooks/useEditRowKeyNavigation";

interface UseExpenseTableArgs {
	onEdit: (expense: ExpenseEntry) => void;
	onDelete: (id: string) => void;
	showNotification?: ShowNotificationFn;
}

/**
 * Shared table-row editing state/handlers for both the real expense
 * table and the budget simulator table. Returns TableHandlers<ExpenseEntry>
 * directly so callers never need to cast (previously required
 * `as unknown as TableHandlers<ExpenseEntry>` before ExpenseTableHandlers
 * was removed). Delete-confirmation and row key navigation are handled
 * by useConfirmedDelete / useEditRowKeyNavigation respectively.
 */
const useExpenseTable = ({
	onEdit,
	onDelete,
	showNotification,
}: UseExpenseTableArgs) => {
	const [editingId, setEditingId] = useState<string | null>(null);
	const [editForm, setEditForm] = useState<ExpenseEntry | null>(null);
	const editRowRef = useRef<HTMLTableRowElement | null>(null);

	const handleStartEdit = (expense: ExpenseEntry) => {
		if (expense.isAutoGenerated) return;
		setEditingId(expense.id);
		setEditForm({ ...expense });
	};

	const handleCancelEdit = () => {
		setEditingId(null);
		setEditForm(null);
	};

	const handleSaveEdit = () => {
		if (editForm) {
			onEdit(editForm);
			setEditingId(null);
			setEditForm(null);
		}
	};

	const handleEditChange = (
		field: keyof ExpenseEntry,
		value: string | number,
	) => {
		if (!editForm) return;

		setEditForm({
			...editForm,
			[field]:
				field === "amount"
					? parseFloat(value as string) || 0
					: field === "quantity"
						? parseInt(value as string, 10) || 0
						: value,
		});
	};

	const { confirmationModal, handleDelete, handleRemoveItem } =
		useConfirmedDelete(onDelete, showNotification);

	const handleKeyDown = useEditRowKeyNavigation(
		editingId,
		editRowRef,
		handleSaveEdit,
		handleCancelEdit,
	);

	const displayQuantity = (
		quantity: number | undefined,
		unit: string | undefined,
	) => {
		if (
			quantity === undefined ||
			Number.isNaN(quantity) ||
			!quantity ||
			!unit
		) {
			return "-";
		}
		return `${quantity} ${unit}`;
	};

	const handlers: TableHandlers<ExpenseEntry> & {
		handleRemoveItem: (id: string, name?: string) => Promise<void>;
	} = {
		handleStartEdit,
		handleCancelEdit,
		handleSaveEdit,
		handleEditChange,
		handleDelete,
		handleRemoveItem,
		handleKeyDown,
		displayQuantity,
	};

	return { editingId, editForm, editRowRef, confirmationModal, handlers };
};

export default useExpenseTable;
